function res = correctModeOrder(modetype, nu)
% Checks that NU is allowed for such MODETYPE.

% Check that mode type is known
switch lower(modetype)
    case {'te'; 'tm'; 'tsaote'; 'tsaotm'; 'hybrid'; 'tsaohybrid'; 'monerie'; 'erdogan'; 'zhang'}
        % ok
    otherwise
        error('%s: UNKNOWN MODE TYPE (%s)\n', mfilename, modetype)
end;

% Check that mode order is >0 for hybrid or 0 for TE and TM 
res = (strcmpi(modetype, 'TE') || ...
    strcmpi(modetype, 'TM') ||...
     strcmpi(modetype , 'tsaote') ||...
     strcmpi(modetype , 'tsaotm')) && (nu == 0) || ...
    (strcmpi(modetype , 'hybrid') ||  strcmpi(modetype , 'tsaohybrid') ||...
    strcmpi(modetype , 'erdogan') || strcmpi(modetype , 'zhang')) ...
    && nu > 0 || ...
    strcmpi(modetype , 'monerie');

